"""Compliance chat API route — Phase 7 hybrid search + LLM re-ranking.

Purpose
-------
Exposes ``POST /api/v1/chat`` as the entry point for natural language
compliance questions. The endpoint builds the RAG pipeline, runs it, logs the
query to PostgreSQL, and returns a structured ``RAGResponse``.

Architecture Integration
------------------------
* Phase 7: ``_get_pipeline`` builds the full retrieval stack:
    QdrantRetriever + BM25Retriever → HybridRetriever (RRF) → RerankedRetriever (LLM)
  The pipeline and endpoint are otherwise unchanged from Phase 6.
* Phase 8+: this route will delegate to a LangGraph intent router. The
  endpoint signature (``ChatRequest`` in, ``RAGResponse`` out) stays the same
  so the frontend Streamlit page requires no changes during that upgrade.

Pipeline instances are created lazily on first request and cached for the
process lifetime via ``@lru_cache``. This avoids repeating ``genai.configure``
and ``QdrantClient`` handshakes on every HTTP request.
"""

from __future__ import annotations

import logging
from functools import lru_cache

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from backend.app.api.deps import get_session
from backend.app.core.config import get_settings
from backend.app.db.qdrant import get_qdrant_client
from backend.app.models.query_log import QueryLog
from backend.app.repositories.base import BaseRepository
from backend.app.schemas.query_log import QueryLogCreate
from backend.app.schemas.rag import ChatRequest, RAGResponse
from backend.app.services.bm25_retriever import BM25Retriever
from backend.app.services.embeddings import get_embeddings_service
from backend.app.services.generation import GeminiClient
from backend.app.services.hybrid_retriever import HybridRetriever
from backend.app.services.rag import BaselineRAGPipeline
from backend.app.services.reranker import LLMReranker, RerankedRetriever
from backend.app.services.retrieval import QdrantRetriever

router = APIRouter(prefix="/chat", tags=["Compliance Chat"])
logger = logging.getLogger(__name__)

_query_log_repo: BaseRepository = BaseRepository(QueryLog)


# ── Pipeline factory ───────────────────────────────────────────────────────────

@lru_cache(maxsize=1)
def _get_pipeline() -> BaselineRAGPipeline:
    """Build and cache the Phase 7 retrieval stack for the process lifetime.

    Stack: QdrantRetriever + BM25Retriever → HybridRetriever (RRF)
                                           → RerankedRetriever (LLM, top-20 → top-5)
                                           → BaselineRAGPipeline → GeminiClient

    ``lru_cache`` ensures all heavy construction (Qdrant client, BM25 index,
    Gemini client) happens exactly once per process.
    Call ``_get_pipeline.cache_clear()`` in tests.
    """
    settings = get_settings()
    embeddings = get_embeddings_service(settings=settings)
    qdrant = get_qdrant_client()

    dense = QdrantRetriever(qdrant_client=qdrant, embeddings_service=embeddings)
    sparse = BM25Retriever()                          # loads chunks.jsonl; ~170 docs
    hybrid = HybridRetriever(dense=dense, sparse=sparse)

    gemini = GeminiClient(settings=settings)          # also used as reranker LLM
    reranker = LLMReranker(client=gemini)
    retriever = RerankedRetriever(base=hybrid, reranker=reranker, candidate_pool=20)

    return BaselineRAGPipeline(retriever=retriever, gemini_client=gemini)


# ── Endpoint ───────────────────────────────────────────────────────────────────

@router.post(
    "",
    response_model=RAGResponse,
    summary="Compliance chat",
    description=(
        "Ask a natural language compliance question. "
        "The system retrieves relevant ADGM regulations via semantic search "
        "and returns a cited answer generated by Gemini."
    ),
)
def compliance_chat(
    request: ChatRequest,
    session: Session = Depends(get_session),
) -> RAGResponse:
    """Phase 7: embed → Qdrant+BM25 RRF → LLM re-rank → Gemini/Groq → cited answer."""
    try:
        response = _get_pipeline().run(request)
    except Exception as exc:
        logger.error("RAG pipeline failed: %s", exc, exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Compliance chat failed: {exc}",
        ) from exc

    _persist_query_log(session, request, response)
    return response


# ── Logging ────────────────────────────────────────────────────────────────────

def _persist_query_log(
    session: Session,
    request: ChatRequest,
    response: RAGResponse,
) -> None:
    """Write the query and response to the ``query_logs`` table.

    Failures here are logged but never raised — a logging error must never
    degrade the user-facing response.
    """
    try:
        log_entry = QueryLogCreate(
            query_type="compliance_chat",
            question=request.question,
            response_text=response.answer,
            latency_ms=int(response.latency_ms),
            model_name=response.model,
            retrieval_payload={
                "collections_searched": response.collections_searched,
                "chunks_used": response.chunks_used,
                "top_k_requested": request.top_k,
                "chunks": [
                    {
                        "chunk_id": c.chunk_id,
                        "collection": c.collection,
                        "score": c.score,
                        "rule_reference": c.rule_reference,
                    }
                    for c in response.retrieved_chunks
                ],
            },
            citation_payload={
                "sources": [s.model_dump() for s in response.sources],
            },
        )
        _query_log_repo.create(session, log_entry)
    except Exception as exc:
        logger.warning("Failed to persist query log: %s", exc)
