"use client";
import { useState } from "react";
import {
  BarChart3, Play, Eye, CheckCircle2, XCircle,
  AlertTriangle, Database, Clock, Loader2, Table2,
} from "lucide-react";
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid,
  Tooltip, ResponsiveContainer, Cell,
} from "recharts";
import TopBar from "@/components/layout/TopBar";
import { runAnalyticsQuery } from "@/lib/api";
import type { AnalyticsResult } from "@/types";
import { highlightSql, formatLatency } from "@/lib/utils";

const EXAMPLE_QUERIES = [
  "How many compliance reviews have been completed this month?",
  "Show me the top 5 documents by violation count",
  "What is the average compliance score across all reviews?",
  "List all critical violations detected in the last 30 days",
  "How many clauses have been generated by document type?",
];

function SqlBlock({ sql }: { sql: string }) {
  return (
    <pre
      className="sql-block overflow-x-auto"
      dangerouslySetInnerHTML={{ __html: highlightSql(sql) }}
    />
  );
}

function ResultsTable({ columns, rows }: { columns: string[]; rows: Record<string, unknown>[] }) {
  if (!rows.length) return <p className="text-sm text-[var(--text-3)] text-center py-6">Query returned 0 rows.</p>;

  const numericCol = columns.find(c =>
    rows.every(r => typeof r[c] === "number" || (typeof r[c] === "string" && !isNaN(Number(r[c]))))
  );
  const labelCol = columns.find(c => c !== numericCol);
  const canChart = !!(numericCol && labelCol && rows.length <= 20);

  return (
    <div className="space-y-5">
      {canChart && (
        <div className="card p-4">
          <p className="section-label mb-3">{numericCol}</p>
          <ResponsiveContainer width="100%" height={220}>
            <BarChart data={rows} margin={{ top: 4, right: 8, bottom: 4, left: 8 }}>
              <CartesianGrid strokeDasharray="3 3" stroke="#EDE9DF" />
              <XAxis dataKey={labelCol!} tick={{ fill: "#9B9083", fontSize: 10 }} />
              <YAxis tick={{ fill: "#9B9083", fontSize: 10 }} />
              <Tooltip
                contentStyle={{ background: "#FFFFFF", border: "1px solid #EDE9DF", borderRadius: 8, fontSize: 11 }}
                labelStyle={{ color: "#D97706", fontWeight: 600 }}
              />
              <Bar dataKey={numericCol!} radius={[4, 4, 0, 0]}>
                {rows.map((_, i) => (
                  <Cell key={i} fill={`hsl(${35 + i * 18}, 80%, ${55 + (i % 3) * 8}%)`} />
                ))}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </div>
      )}

      <div className="overflow-x-auto rounded-xl border border-[var(--border)]">
        <table className="w-full text-xs">
          <thead>
            <tr className="border-b border-[var(--border)] bg-[var(--surface-alt)]">
              {columns.map(c => (
                <th key={c} className="text-left px-4 py-2.5 text-[var(--text-2)] font-semibold capitalize whitespace-nowrap">
                  {c.replace(/_/g, " ")}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {rows.map((row, i) => (
              <tr key={i} className="border-b border-[var(--border)] hover:bg-amber-50/40 transition-colors">
                {columns.map(c => (
                  <td key={c} className="px-4 py-2.5 text-[var(--text-2)] whitespace-nowrap max-w-[260px] truncate">
                    {String(row[c] ?? "—")}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

export default function AnalyticsPage() {
  const [question, setQuestion] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<AnalyticsResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [approving, setApproving] = useState(false);

  async function handleQuery(previewOnly = true) {
    if (!question.trim() || loading) return;
    setError(null); setApproving(false); setLoading(true);
    try {
      const r = await runAnalyticsQuery(question, previewOnly);
      setResult(r);
      if (previewOnly && r.sql_safe) setApproving(true);
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : "Query failed");
    } finally { setLoading(false); }
  }

  async function handleApprove() {
    if (!result?.generated_sql) return;
    setApproving(false); setLoading(true);
    try { setResult(await runAnalyticsQuery(question, false, result.generated_sql)); }
    catch (e: unknown) { setError(e instanceof Error ? e.message : "Execution failed"); }
    finally { setLoading(false); }
  }

  function reset() { setResult(null); setError(null); setApproving(false); setQuestion(""); }

  return (
    <div className="flex flex-col h-full overflow-hidden">
      <TopBar title="Analytics" subtitle="Ask data questions in plain English and explore your compliance data" />

      <div className="flex-1 overflow-y-auto px-6 py-6 space-y-5 page-enter">
        {/* Query input */}
        <div className="card p-5 space-y-4">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-coral-50 border border-coral-100 flex items-center justify-center" style={{ background: "#FFF7ED", borderColor: "#FED7AA" }}>
              <BarChart3 size={14} className="text-orange-600" />
            </div>
            <h3 className="font-display text-sm font-semibold text-[var(--text)]">Ask a data question</h3>
          </div>

          <div className="flex gap-3">
            <input
              value={question}
              onChange={e => setQuestion(e.target.value)}
              onKeyDown={e => e.key === "Enter" && handleQuery(true)}
              placeholder="e.g. How many reviews have a compliance score below 60?"
              className="flex-1 min-w-0 bg-[var(--surface-alt)] border border-[var(--border)] rounded-xl px-4 py-2.5 text-sm text-[var(--text)] placeholder:text-[var(--text-3)] focus:outline-none focus:border-amber-300 focus:bg-white transition-all"
            />
            <button
              onClick={() => handleQuery(true)}
              disabled={!question.trim() || loading}
              className="flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-medium transition-all whitespace-nowrap border"
              style={
                question.trim() && !loading
                  ? { background: "#FFF7ED", borderColor: "#FED7AA", color: "#EA580C" }
                  : { background: "var(--surface-alt)", borderColor: "var(--border)", color: "var(--text-3)", cursor: "not-allowed" }
              }
            >
              {loading ? <Loader2 size={13} className="animate-spin" /> : <Eye size={13} />}
              {loading ? "Processing…" : "Preview SQL"}
            </button>
          </div>

          <div className="flex flex-wrap gap-1.5">
            {EXAMPLE_QUERIES.map(q => (
              <button
                key={q}
                onClick={() => setQuestion(q)}
                className="text-[10.5px] px-2.5 py-1 rounded-lg bg-[var(--surface-alt)] border border-[var(--border)] text-[var(--text-3)] hover:text-amber-700 hover:border-amber-200 hover:bg-amber-50 transition-all"
              >
                {q.length > 50 ? q.slice(0, 48) + "…" : q}
              </button>
            ))}
          </div>
        </div>

        {error && (
          <div className="card rounded-xl p-4 border-rose-200 text-sm text-rose-700 flex items-start gap-2" style={{ background: "#FFF1F2" }}>
            <XCircle size={13} className="flex-shrink-0 mt-0.5" /> {error}
          </div>
        )}

        {result && (
          <div className="space-y-4">
            {/* Safety blocked */}
            {!result.sql_safe && (
              <div className="card rounded-xl p-4 border-rose-200 flex items-start gap-3" style={{ background: "#FFF1F2" }}>
                <AlertTriangle size={15} className="text-rose-500 flex-shrink-0 mt-0.5" />
                <div>
                  <p className="text-sm font-medium text-rose-700">Query Blocked</p>
                  <p className="text-xs text-rose-500 mt-0.5">{result.sql_rejection_reason}</p>
                </div>
              </div>
            )}

            {/* SQL + approval */}
            {result.generated_sql && result.sql_safe && (
              <div className="card rounded-2xl overflow-hidden">
                <div className="flex items-center justify-between px-5 py-3 border-b border-[var(--border)] bg-[var(--surface-alt)]">
                  <span className="text-xs font-medium text-[var(--text-2)] flex items-center gap-1.5">
                    <Database size={11} className="text-orange-500" /> Generated SQL
                  </span>
                  {approving && (
                    <div className="flex items-center gap-2">
                      <button
                        onClick={handleApprove}
                        className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-all border"
                        style={{ background: "#ECFDF5", borderColor: "#A7F3D0", color: "#059669" }}
                      >
                        <Play size={10} /> Approve & Run
                      </button>
                      <button
                        onClick={reset}
                        className="btn-outline text-xs py-1.5 px-3 flex items-center gap-1.5"
                      >
                        <XCircle size={10} /> Cancel
                      </button>
                    </div>
                  )}
                  {!approving && result.query_results !== null && (
                    <span className="text-xs text-jade-600 flex items-center gap-1">
                      <CheckCircle2 size={10} /> Executed
                    </span>
                  )}
                </div>
                <div className="p-5">
                  <SqlBlock sql={result.generated_sql} />
                  {approving && (
                    <p className="text-xs text-amber-600 mt-3 flex items-center gap-1.5">
                      <AlertTriangle size={10} /> Review the SQL above before approving execution.
                    </p>
                  )}
                </div>
              </div>
            )}

            {/* Answer narrative */}
            {result.answer && (
              <div className="card p-5">
                <div className="flex items-center gap-1.5 mb-3">
                  <BarChart3 size={12} className="text-orange-500" />
                  <span className="section-label">Answer</span>
                  {result.row_count != null && (
                    <span className="ml-auto text-[10.5px] text-[var(--text-3)] flex items-center gap-1">
                      <Table2 size={9} /> {result.row_count} rows
                    </span>
                  )}
                </div>
                <p className="text-sm text-[var(--text-2)] leading-relaxed">{result.answer}</p>
              </div>
            )}

            {/* Results table */}
            {result.query_results && result.columns && result.query_results.length > 0 && (
              <div className="card p-5">
                <div className="flex items-center gap-1.5 mb-4">
                  <Table2 size={12} className="text-orange-500" />
                  <span className="section-label">Results</span>
                  <span className="ml-auto text-[10.5px] text-[var(--text-3)]">{result.row_count} rows returned</span>
                </div>
                <ResultsTable columns={result.columns} rows={result.query_results as Record<string, unknown>[]} />
              </div>
            )}

            <div className="flex items-center justify-between text-[11px] text-[var(--text-3)]">
              <span className="flex items-center gap-1"><Clock size={9} /> {result.model}</span>
              <button onClick={reset} className="hover:text-amber-700 transition-colors">← New query</button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
