"use client";
import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  BarChart3, Play, Eye, CheckCircle2, XCircle,
  AlertTriangle, Database, Clock, Cpu, Table2,
} from "lucide-react";
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid,
  Tooltip, ResponsiveContainer, Cell,
} from "recharts";
import TopBar from "@/components/layout/TopBar";
import { runAnalyticsQuery } from "@/lib/api";
import type { AnalyticsResult } from "@/types";
import { cn, highlightSql, formatLatency } from "@/lib/utils";

const EXAMPLE_QUERIES = [
  "How many compliance reviews have been completed this month?",
  "Show me the top 5 documents by violation count",
  "What is the average compliance score across all reviews?",
  "List all critical violations detected in the last 30 days",
  "How many clauses have been generated by document type?",
];

function SqlBlock({ sql }: { sql: string }) {
  return (
    <pre
      className="bg-navy-950/80 border border-white/6 rounded-xl p-4 text-xs font-mono leading-relaxed overflow-x-auto"
      dangerouslySetInnerHTML={{ __html: highlightSql(sql) }}
    />
  );
}

function ResultsTable({ columns, rows }: { columns: string[]; rows: Record<string, unknown>[] }) {
  if (!rows.length) return <p className="text-sm text-slate-500 text-center py-6">Query returned 0 rows.</p>;

  // Detect if any column looks numeric for a bar chart
  const numericCol = columns.find(c =>
    rows.every(r => typeof r[c] === "number" || (typeof r[c] === "string" && !isNaN(Number(r[c]))))
  );
  const labelCol = columns.find(c => c !== numericCol);
  const canChart = !!(numericCol && labelCol && rows.length <= 20);

  return (
    <div className="space-y-5">
      {/* Chart */}
      {canChart && (
        <div className="glass rounded-xl p-4">
          <p className="text-xs text-slate-500 mb-3">Visual — {numericCol}</p>
          <ResponsiveContainer width="100%" height={220}>
            <BarChart data={rows} margin={{ top: 4, right: 8, bottom: 4, left: 8 }}>
              <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.04)" />
              <XAxis dataKey={labelCol!} tick={{ fill: "#6b7ea8", fontSize: 10 }} />
              <YAxis tick={{ fill: "#6b7ea8", fontSize: 10 }} />
              <Tooltip
                contentStyle={{ background: "#0d1526", border: "1px solid rgba(212,160,48,0.2)", borderRadius: 8, fontSize: 11 }}
                labelStyle={{ color: "#f0c050" }}
              />
              <Bar dataKey={numericCol!} radius={[4, 4, 0, 0]}>
                {rows.map((_, i) => (
                  <Cell key={i} fill={`hsl(${200 + i * 15}, 70%, 60%)`} />
                ))}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </div>
      )}

      {/* Table */}
      <div className="overflow-x-auto rounded-xl border border-white/6">
        <table className="w-full text-xs">
          <thead>
            <tr className="border-b border-white/6 bg-navy-800/60">
              {columns.map(c => (
                <th key={c} className="text-left px-4 py-2.5 text-slate-400 font-semibold capitalize whitespace-nowrap">
                  {c.replace(/_/g, " ")}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {rows.map((row, i) => (
              <tr key={i} className="border-b border-white/4 hover:bg-white/2 transition-colors">
                {columns.map(c => (
                  <td key={c} className="px-4 py-2.5 text-slate-300 whitespace-nowrap max-w-[260px] truncate">
                    {String(row[c] ?? "—")}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

export default function AnalyticsPage() {
  const [question, setQuestion] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<AnalyticsResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [approving, setApproving] = useState(false);

  async function handleQuery(previewOnly = true) {
    if (!question.trim() || loading) return;
    setError(null);
    setApproving(false);
    setLoading(true);
    try {
      const r = await runAnalyticsQuery(question, previewOnly);
      setResult(r);
      if (previewOnly && r.sql_safe) setApproving(true);
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : "Query failed");
    } finally {
      setLoading(false);
    }
  }

  async function handleApprove() {
    if (!result?.generated_sql) return;
    setApproving(false);
    setLoading(true);
    try {
      const r = await runAnalyticsQuery(question, false, result.generated_sql);
      setResult(r);
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : "Execution failed");
    } finally {
      setLoading(false);
    }
  }

  function reset() {
    setResult(null);
    setError(null);
    setApproving(false);
    setQuestion("");
  }

  return (
    <div className="flex flex-col h-full overflow-hidden">
      <TopBar title="Analytics" subtitle="Natural language → SQL → Human approval → Results" />

      <div className="flex-1 overflow-y-auto px-6 py-6 space-y-5 page-enter">
        {/* Query input */}
        <div className="glass rounded-2xl p-5 space-y-4">
          <div className="flex items-center gap-2">
            <BarChart3 size={16} className="text-orange-400" />
            <h3 className="text-sm font-semibold text-white">Ask a data question</h3>
          </div>

          <div className="flex gap-3">
            <input
              value={question}
              onChange={e => setQuestion(e.target.value)}
              onKeyDown={e => e.key === "Enter" && handleQuery(true)}
              placeholder="e.g. How many reviews have a compliance score below 60?"
              className="flex-1 bg-navy-800/80 border border-white/8 rounded-xl px-4 py-2.5 text-sm text-white placeholder:text-slate-600 focus:outline-none focus:border-orange-400/40 transition-all"
            />
            <motion.button
              whileHover={{ scale: 1.03 }}
              whileTap={{ scale: 0.97 }}
              onClick={() => handleQuery(true)}
              disabled={!question.trim() || loading}
              className={cn(
                "flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-medium transition-all whitespace-nowrap",
                question.trim() && !loading
                  ? "bg-orange-400/15 border border-orange-400/25 text-orange-300 hover:bg-orange-400/25"
                  : "bg-navy-700/50 border border-white/5 text-slate-600 cursor-not-allowed"
              )}
            >
              {loading ? <Cpu size={14} className="animate-spin-slow" /> : <Eye size={14} />}
              {loading ? "Processing…" : "Preview SQL"}
            </motion.button>
          </div>

          {/* Example queries */}
          <div className="flex flex-wrap gap-1.5">
            {EXAMPLE_QUERIES.map(q => (
              <button
                key={q}
                onClick={() => setQuestion(q)}
                className="text-[10px] px-2.5 py-1 rounded-lg bg-navy-800/60 border border-white/5 text-slate-500 hover:text-slate-300 hover:border-white/12 transition-all"
              >
                {q.length > 50 ? q.slice(0, 48) + "…" : q}
              </button>
            ))}
          </div>
        </div>

        {error && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="rounded-xl border border-crimson-500/30 bg-crimson-500/8 p-4 text-sm text-crimson-400 flex items-start gap-2"
          >
            <XCircle size={14} className="flex-shrink-0 mt-0.5" />
            {error}
          </motion.div>
        )}

        <AnimatePresence mode="wait">
          {result && (
            <motion.div
              key="result"
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              className="space-y-4"
            >
              {/* SQL safety status */}
              {!result.sql_safe && (
                <div className="rounded-xl border border-crimson-500/30 bg-crimson-500/8 p-4 flex items-start gap-3">
                  <AlertTriangle size={16} className="text-crimson-400 flex-shrink-0 mt-0.5" />
                  <div>
                    <p className="text-sm font-medium text-crimson-400">Query Blocked</p>
                    <p className="text-xs text-slate-500 mt-0.5">{result.sql_rejection_reason}</p>
                  </div>
                </div>
              )}

              {/* SQL preview + approval */}
              {result.generated_sql && result.sql_safe && (
                <div className="glass rounded-2xl overflow-hidden">
                  <div className="flex items-center justify-between px-5 py-3 border-b border-white/5">
                    <span className="text-xs font-medium text-slate-400 flex items-center gap-1.5">
                      <Database size={12} className="text-orange-400" /> Generated SQL
                    </span>
                    {approving && (
                      <div className="flex items-center gap-2">
                        <motion.button
                          whileHover={{ scale: 1.05 }}
                          whileTap={{ scale: 0.95 }}
                          onClick={handleApprove}
                          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-jade-400/15 border border-jade-400/25 text-jade-400 text-xs font-medium hover:bg-jade-400/25 transition-all"
                        >
                          <Play size={11} /> Approve & Run
                        </motion.button>
                        <button
                          onClick={reset}
                          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-navy-700/60 border border-white/8 text-slate-400 text-xs hover:text-slate-200 transition-all"
                        >
                          <XCircle size={11} /> Cancel
                        </button>
                      </div>
                    )}
                    {!approving && result.query_results !== null && (
                      <span className="text-xs text-jade-400 flex items-center gap-1">
                        <CheckCircle2 size={11} /> Executed
                      </span>
                    )}
                  </div>
                  <div className="p-5">
                    <SqlBlock sql={result.generated_sql} />
                    {approving && (
                      <p className="text-xs text-gold-400/80 mt-3 flex items-center gap-1.5">
                        <AlertTriangle size={11} /> Review the SQL above before approving execution.
                      </p>
                    )}
                  </div>
                </div>
              )}

              {/* Answer narrative */}
              {result.answer && (
                <div className="glass rounded-2xl p-5">
                  <div className="flex items-center gap-1.5 mb-3">
                    <BarChart3 size={13} className="text-orange-400" />
                    <span className="text-xs font-medium text-slate-400">Answer</span>
                    {result.row_count !== null && result.row_count !== undefined && (
                      <span className="ml-auto text-xs text-slate-600 flex items-center gap-1">
                        <Table2 size={10} /> {result.row_count} rows
                      </span>
                    )}
                  </div>
                  <p className="text-sm text-slate-300 leading-relaxed">{result.answer}</p>
                </div>
              )}

              {/* Results table */}
              {result.query_results && result.columns && result.query_results.length > 0 && (
                <div className="glass rounded-2xl p-5">
                  <div className="flex items-center gap-1.5 mb-4">
                    <Table2 size={13} className="text-orange-400" />
                    <span className="text-xs font-medium text-slate-400">Results</span>
                    <span className="ml-auto text-xs text-slate-600">{result.row_count} rows returned</span>
                  </div>
                  <ResultsTable columns={result.columns} rows={result.query_results as Record<string, unknown>[]} />
                </div>
              )}

              <div className="flex items-center justify-between text-xs text-slate-600">
                <span className="flex items-center gap-1"><Clock size={10} /> Model: {result.model}</span>
                <button onClick={reset} className="hover:text-slate-400 transition-colors">← New query</button>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}
